const hourly = {
  "@context": [
    "https://raw.githubusercontent.com/geojson/geojson-ld/master/contexts/geojson-base.jsonld",
    {
      wx: "https://api.weather.gov/ontology#",
      geo: "http://www.opengis.net/ont/geosparql#",
      unit: "http://codes.wmo.int/common/unit/",
      "@vocab": "https://api.weather.gov/ontology#"
    }
  ],
  type: "Feature",
  geometry: {
    type: "GeometryCollection",
    geometries: [
      {
        type: "Point",
        coordinates: [-97.094408400000006, 39.7559738]
      },
      {
        type: "Polygon",
        coordinates: [
          [
            [-97.1089731, 39.766826299999998],
            [-97.108526900000001, 39.744778799999999],
            [-97.079846700000004, 39.745119500000001],
            [-97.08028680000001, 39.767167000000001],
            [-97.1089731, 39.766826299999998]
          ]
        ]
      }
    ]
  },
  properties: {
    updated: "2020-02-01T23:26:24+00:00",
    units: "us",
    forecastGenerator: "HourlyForecastGenerator",
    generatedAt: "2020-02-02T02:31:04+00:00",
    updateTime: "2020-02-01T23:26:24+00:00",
    validTimes: "2020-02-01T17:00:00+00:00/P7DT8H",
    elevation: {
      value: 441.96000000000004,
      unitCode: "unit:m"
    },
    periods: [
      {
        number: 1,
        name: "",
        startTime: "2020-02-01T20:00:00-06:00",
        endTime: "2020-02-01T21:00:00-06:00",
        isDaytime: false,
        temperature: 48,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/night/few?size=small",
        shortForecast: "Mostly Clear",
        detailedForecast: ""
      },
      {
        number: 2,
        name: "",
        startTime: "2020-02-01T21:00:00-06:00",
        endTime: "2020-02-01T22:00:00-06:00",
        isDaytime: false,
        temperature: 47,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/night/few?size=small",
        shortForecast: "Mostly Clear",
        detailedForecast: ""
      },
      {
        number: 3,
        name: "",
        startTime: "2020-02-01T22:00:00-06:00",
        endTime: "2020-02-01T23:00:00-06:00",
        isDaytime: false,
        temperature: 46,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/night/few?size=small",
        shortForecast: "Mostly Clear",
        detailedForecast: ""
      },
      {
        number: 4,
        name: "",
        startTime: "2020-02-01T23:00:00-06:00",
        endTime: "2020-02-02T00:00:00-06:00",
        isDaytime: false,
        temperature: 46,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/night/skc?size=small",
        shortForecast: "Clear",
        detailedForecast: ""
      },
      {
        number: 5,
        name: "",
        startTime: "2020-02-02T00:00:00-06:00",
        endTime: "2020-02-02T01:00:00-06:00",
        isDaytime: false,
        temperature: 45,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/night/skc?size=small",
        shortForecast: "Clear",
        detailedForecast: ""
      },
      {
        number: 6,
        name: "",
        startTime: "2020-02-02T01:00:00-06:00",
        endTime: "2020-02-02T02:00:00-06:00",
        isDaytime: false,
        temperature: 43,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/night/skc?size=small",
        shortForecast: "Clear",
        detailedForecast: ""
      },
      {
        number: 7,
        name: "",
        startTime: "2020-02-02T02:00:00-06:00",
        endTime: "2020-02-02T03:00:00-06:00",
        isDaytime: false,
        temperature: 42,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/night/skc?size=small",
        shortForecast: "Clear",
        detailedForecast: ""
      },
      {
        number: 8,
        name: "",
        startTime: "2020-02-02T03:00:00-06:00",
        endTime: "2020-02-02T04:00:00-06:00",
        isDaytime: false,
        temperature: 40,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/night/skc?size=small",
        shortForecast: "Clear",
        detailedForecast: ""
      },
      {
        number: 9,
        name: "",
        startTime: "2020-02-02T04:00:00-06:00",
        endTime: "2020-02-02T05:00:00-06:00",
        isDaytime: false,
        temperature: 39,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/night/skc?size=small",
        shortForecast: "Clear",
        detailedForecast: ""
      },
      {
        number: 10,
        name: "",
        startTime: "2020-02-02T05:00:00-06:00",
        endTime: "2020-02-02T06:00:00-06:00",
        isDaytime: false,
        temperature: 37,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/night/few?size=small",
        shortForecast: "Mostly Clear",
        detailedForecast: ""
      },
      {
        number: 11,
        name: "",
        startTime: "2020-02-02T06:00:00-06:00",
        endTime: "2020-02-02T07:00:00-06:00",
        isDaytime: true,
        temperature: 36,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/day/few?size=small",
        shortForecast: "Sunny",
        detailedForecast: ""
      },
      {
        number: 12,
        name: "",
        startTime: "2020-02-02T07:00:00-06:00",
        endTime: "2020-02-02T08:00:00-06:00",
        isDaytime: true,
        temperature: 36,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/day/few?size=small",
        shortForecast: "Sunny",
        detailedForecast: ""
      },
      {
        number: 13,
        name: "",
        startTime: "2020-02-02T08:00:00-06:00",
        endTime: "2020-02-02T09:00:00-06:00",
        isDaytime: true,
        temperature: 37,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/day/few?size=small",
        shortForecast: "Sunny",
        detailedForecast: ""
      },
      {
        number: 14,
        name: "",
        startTime: "2020-02-02T09:00:00-06:00",
        endTime: "2020-02-02T10:00:00-06:00",
        isDaytime: true,
        temperature: 41,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/day/few?size=small",
        shortForecast: "Sunny",
        detailedForecast: ""
      },
      {
        number: 15,
        name: "",
        startTime: "2020-02-02T10:00:00-06:00",
        endTime: "2020-02-02T11:00:00-06:00",
        isDaytime: true,
        temperature: 46,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/day/few?size=small",
        shortForecast: "Sunny",
        detailedForecast: ""
      },
      {
        number: 16,
        name: "",
        startTime: "2020-02-02T11:00:00-06:00",
        endTime: "2020-02-02T12:00:00-06:00",
        isDaytime: true,
        temperature: 52,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/day/skc?size=small",
        shortForecast: "Sunny",
        detailedForecast: ""
      },
      {
        number: 17,
        name: "",
        startTime: "2020-02-02T12:00:00-06:00",
        endTime: "2020-02-02T13:00:00-06:00",
        isDaytime: true,
        temperature: 58,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/day/skc?size=small",
        shortForecast: "Sunny",
        detailedForecast: ""
      },
      {
        number: 18,
        name: "",
        startTime: "2020-02-02T13:00:00-06:00",
        endTime: "2020-02-02T14:00:00-06:00",
        isDaytime: true,
        temperature: 62,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/day/skc?size=small",
        shortForecast: "Sunny",
        detailedForecast: ""
      },
      {
        number: 19,
        name: "",
        startTime: "2020-02-02T14:00:00-06:00",
        endTime: "2020-02-02T15:00:00-06:00",
        isDaytime: true,
        temperature: 64,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "SW",
        icon: "https://api.weather.gov/icons/land/day/skc?size=small",
        shortForecast: "Sunny",
        detailedForecast: ""
      },
      {
        number: 20,
        name: "",
        startTime: "2020-02-02T15:00:00-06:00",
        endTime: "2020-02-02T16:00:00-06:00",
        isDaytime: true,
        temperature: 63,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "S",
        icon: "https://api.weather.gov/icons/land/day/skc?size=small",
        shortForecast: "Sunny",
        detailedForecast: ""
      },
      {
        number: 21,
        name: "",
        startTime: "2020-02-02T16:00:00-06:00",
        endTime: "2020-02-02T17:00:00-06:00",
        isDaytime: true,
        temperature: 61,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "E",
        icon: "https://api.weather.gov/icons/land/day/few?size=small",
        shortForecast: "Sunny",
        detailedForecast: ""
      },
      {
        number: 22,
        name: "",
        startTime: "2020-02-02T17:00:00-06:00",
        endTime: "2020-02-02T18:00:00-06:00",
        isDaytime: true,
        temperature: 57,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "E",
        icon: "https://api.weather.gov/icons/land/day/sct?size=small",
        shortForecast: "Mostly Sunny",
        detailedForecast: ""
      },
      {
        number: 23,
        name: "",
        startTime: "2020-02-02T18:00:00-06:00",
        endTime: "2020-02-02T19:00:00-06:00",
        isDaytime: false,
        temperature: 53,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "E",
        icon: "https://api.weather.gov/icons/land/night/sct?size=small",
        shortForecast: "Partly Cloudy",
        detailedForecast: ""
      },
      {
        number: 24,
        name: "",
        startTime: "2020-02-02T19:00:00-06:00",
        endTime: "2020-02-02T20:00:00-06:00",
        isDaytime: false,
        temperature: 49,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "E",
        icon: "https://api.weather.gov/icons/land/night/sct?size=small",
        shortForecast: "Partly Cloudy",
        detailedForecast: ""
      },
      {
        number: 25,
        name: "",
        startTime: "2020-02-02T20:00:00-06:00",
        endTime: "2020-02-02T21:00:00-06:00",
        isDaytime: false,
        temperature: 46,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "E",
        icon: "https://api.weather.gov/icons/land/night/sct?size=small",
        shortForecast: "Partly Cloudy",
        detailedForecast: ""
      },
      {
        number: 26,
        name: "",
        startTime: "2020-02-02T21:00:00-06:00",
        endTime: "2020-02-02T22:00:00-06:00",
        isDaytime: false,
        temperature: 44,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "E",
        icon: "https://api.weather.gov/icons/land/night/sct?size=small",
        shortForecast: "Partly Cloudy",
        detailedForecast: ""
      },
      {
        number: 27,
        name: "",
        startTime: "2020-02-02T22:00:00-06:00",
        endTime: "2020-02-02T23:00:00-06:00",
        isDaytime: false,
        temperature: 42,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/night/bkn?size=small",
        shortForecast: "Mostly Cloudy",
        detailedForecast: ""
      },
      {
        number: 28,
        name: "",
        startTime: "2020-02-02T23:00:00-06:00",
        endTime: "2020-02-03T00:00:00-06:00",
        isDaytime: false,
        temperature: 40,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/night/bkn?size=small",
        shortForecast: "Mostly Cloudy",
        detailedForecast: ""
      },
      {
        number: 29,
        name: "",
        startTime: "2020-02-03T00:00:00-06:00",
        endTime: "2020-02-03T01:00:00-06:00",
        isDaytime: false,
        temperature: 38,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/night/bkn?size=small",
        shortForecast: "Mostly Cloudy",
        detailedForecast: ""
      },
      {
        number: 30,
        name: "",
        startTime: "2020-02-03T01:00:00-06:00",
        endTime: "2020-02-03T02:00:00-06:00",
        isDaytime: false,
        temperature: 37,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/night/bkn?size=small",
        shortForecast: "Mostly Cloudy",
        detailedForecast: ""
      },
      {
        number: 31,
        name: "",
        startTime: "2020-02-03T02:00:00-06:00",
        endTime: "2020-02-03T03:00:00-06:00",
        isDaytime: false,
        temperature: 36,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/night/bkn?size=small",
        shortForecast: "Mostly Cloudy",
        detailedForecast: ""
      },
      {
        number: 32,
        name: "",
        startTime: "2020-02-03T03:00:00-06:00",
        endTime: "2020-02-03T04:00:00-06:00",
        isDaytime: false,
        temperature: 34,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/night/bkn?size=small",
        shortForecast: "Mostly Cloudy",
        detailedForecast: ""
      },
      {
        number: 33,
        name: "",
        startTime: "2020-02-03T04:00:00-06:00",
        endTime: "2020-02-03T05:00:00-06:00",
        isDaytime: false,
        temperature: 33,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/night/bkn?size=small",
        shortForecast: "Mostly Cloudy",
        detailedForecast: ""
      },
      {
        number: 34,
        name: "",
        startTime: "2020-02-03T05:00:00-06:00",
        endTime: "2020-02-03T06:00:00-06:00",
        isDaytime: false,
        temperature: 32,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/night/bkn?size=small",
        shortForecast: "Mostly Cloudy",
        detailedForecast: ""
      },
      {
        number: 35,
        name: "",
        startTime: "2020-02-03T06:00:00-06:00",
        endTime: "2020-02-03T07:00:00-06:00",
        isDaytime: true,
        temperature: 31,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/day/bkn?size=small",
        shortForecast: "Mostly Cloudy",
        detailedForecast: ""
      },
      {
        number: 36,
        name: "",
        startTime: "2020-02-03T07:00:00-06:00",
        endTime: "2020-02-03T08:00:00-06:00",
        isDaytime: true,
        temperature: 31,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/day/bkn?size=small",
        shortForecast: "Mostly Cloudy",
        detailedForecast: ""
      },
      {
        number: 37,
        name: "",
        startTime: "2020-02-03T08:00:00-06:00",
        endTime: "2020-02-03T09:00:00-06:00",
        isDaytime: true,
        temperature: 31,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/day/bkn?size=small",
        shortForecast: "Mostly Cloudy",
        detailedForecast: ""
      },
      {
        number: 38,
        name: "",
        startTime: "2020-02-03T09:00:00-06:00",
        endTime: "2020-02-03T10:00:00-06:00",
        isDaytime: true,
        temperature: 31,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/day/ovc?size=small",
        shortForecast: "Cloudy",
        detailedForecast: ""
      },
      {
        number: 39,
        name: "",
        startTime: "2020-02-03T10:00:00-06:00",
        endTime: "2020-02-03T11:00:00-06:00",
        isDaytime: true,
        temperature: 32,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/day/ovc?size=small",
        shortForecast: "Cloudy",
        detailedForecast: ""
      },
      {
        number: 40,
        name: "",
        startTime: "2020-02-03T11:00:00-06:00",
        endTime: "2020-02-03T12:00:00-06:00",
        isDaytime: true,
        temperature: 32,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/day/ovc?size=small",
        shortForecast: "Cloudy",
        detailedForecast: ""
      },
      {
        number: 41,
        name: "",
        startTime: "2020-02-03T12:00:00-06:00",
        endTime: "2020-02-03T13:00:00-06:00",
        isDaytime: true,
        temperature: 33,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/day/bkn?size=small",
        shortForecast: "Mostly Cloudy",
        detailedForecast: ""
      },
      {
        number: 42,
        name: "",
        startTime: "2020-02-03T13:00:00-06:00",
        endTime: "2020-02-03T14:00:00-06:00",
        isDaytime: true,
        temperature: 34,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/day/ovc?size=small",
        shortForecast: "Cloudy",
        detailedForecast: ""
      },
      {
        number: 43,
        name: "",
        startTime: "2020-02-03T14:00:00-06:00",
        endTime: "2020-02-03T15:00:00-06:00",
        isDaytime: true,
        temperature: 34,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/day/ovc?size=small",
        shortForecast: "Cloudy",
        detailedForecast: ""
      },
      {
        number: 44,
        name: "",
        startTime: "2020-02-03T15:00:00-06:00",
        endTime: "2020-02-03T16:00:00-06:00",
        isDaytime: true,
        temperature: 34,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/day/ovc?size=small",
        shortForecast: "Cloudy",
        detailedForecast: ""
      },
      {
        number: 45,
        name: "",
        startTime: "2020-02-03T16:00:00-06:00",
        endTime: "2020-02-03T17:00:00-06:00",
        isDaytime: true,
        temperature: 34,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/day/ovc?size=small",
        shortForecast: "Cloudy",
        detailedForecast: ""
      },
      {
        number: 46,
        name: "",
        startTime: "2020-02-03T17:00:00-06:00",
        endTime: "2020-02-03T18:00:00-06:00",
        isDaytime: true,
        temperature: 33,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/day/ovc?size=small",
        shortForecast: "Cloudy",
        detailedForecast: ""
      },
      {
        number: 47,
        name: "",
        startTime: "2020-02-03T18:00:00-06:00",
        endTime: "2020-02-03T19:00:00-06:00",
        isDaytime: false,
        temperature: 32,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/night/ovc?size=small",
        shortForecast: "Cloudy",
        detailedForecast: ""
      },
      {
        number: 48,
        name: "",
        startTime: "2020-02-03T19:00:00-06:00",
        endTime: "2020-02-03T20:00:00-06:00",
        isDaytime: false,
        temperature: 31,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/night/ovc?size=small",
        shortForecast: "Cloudy",
        detailedForecast: ""
      },
      {
        number: 49,
        name: "",
        startTime: "2020-02-03T20:00:00-06:00",
        endTime: "2020-02-03T21:00:00-06:00",
        isDaytime: false,
        temperature: 31,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/night/ovc?size=small",
        shortForecast: "Cloudy",
        detailedForecast: ""
      },
      {
        number: 50,
        name: "",
        startTime: "2020-02-03T21:00:00-06:00",
        endTime: "2020-02-03T22:00:00-06:00",
        isDaytime: false,
        temperature: 30,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/night/ovc?size=small",
        shortForecast: "Cloudy",
        detailedForecast: ""
      },
      {
        number: 51,
        name: "",
        startTime: "2020-02-03T22:00:00-06:00",
        endTime: "2020-02-03T23:00:00-06:00",
        isDaytime: false,
        temperature: 29,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/night/ovc?size=small",
        shortForecast: "Cloudy",
        detailedForecast: ""
      },
      {
        number: 52,
        name: "",
        startTime: "2020-02-03T23:00:00-06:00",
        endTime: "2020-02-04T00:00:00-06:00",
        isDaytime: false,
        temperature: 28,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/night/bkn?size=small",
        shortForecast: "Mostly Cloudy",
        detailedForecast: ""
      },
      {
        number: 53,
        name: "",
        startTime: "2020-02-04T00:00:00-06:00",
        endTime: "2020-02-04T01:00:00-06:00",
        isDaytime: false,
        temperature: 27,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/night/snow?size=small",
        shortForecast: "Slight Chance Light Snow",
        detailedForecast: ""
      },
      {
        number: 54,
        name: "",
        startTime: "2020-02-04T01:00:00-06:00",
        endTime: "2020-02-04T02:00:00-06:00",
        isDaytime: false,
        temperature: 26,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/night/snow?size=small",
        shortForecast: "Slight Chance Light Snow",
        detailedForecast: ""
      },
      {
        number: 55,
        name: "",
        startTime: "2020-02-04T02:00:00-06:00",
        endTime: "2020-02-04T03:00:00-06:00",
        isDaytime: false,
        temperature: 26,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/night/snow?size=small",
        shortForecast: "Slight Chance Light Snow",
        detailedForecast: ""
      },
      {
        number: 56,
        name: "",
        startTime: "2020-02-04T03:00:00-06:00",
        endTime: "2020-02-04T04:00:00-06:00",
        isDaytime: false,
        temperature: 25,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/night/snow?size=small",
        shortForecast: "Slight Chance Light Snow",
        detailedForecast: ""
      },
      {
        number: 57,
        name: "",
        startTime: "2020-02-04T04:00:00-06:00",
        endTime: "2020-02-04T05:00:00-06:00",
        isDaytime: false,
        temperature: 25,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/night/snow?size=small",
        shortForecast: "Slight Chance Light Snow",
        detailedForecast: ""
      },
      {
        number: 58,
        name: "",
        startTime: "2020-02-04T05:00:00-06:00",
        endTime: "2020-02-04T06:00:00-06:00",
        isDaytime: false,
        temperature: 24,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/night/snow?size=small",
        shortForecast: "Slight Chance Light Snow",
        detailedForecast: ""
      },
      {
        number: 59,
        name: "",
        startTime: "2020-02-04T06:00:00-06:00",
        endTime: "2020-02-04T07:00:00-06:00",
        isDaytime: true,
        temperature: 24,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/day/snow?size=small",
        shortForecast: "Chance Light Snow",
        detailedForecast: ""
      },
      {
        number: 60,
        name: "",
        startTime: "2020-02-04T07:00:00-06:00",
        endTime: "2020-02-04T08:00:00-06:00",
        isDaytime: true,
        temperature: 24,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/day/snow?size=small",
        shortForecast: "Chance Light Snow",
        detailedForecast: ""
      },
      {
        number: 61,
        name: "",
        startTime: "2020-02-04T08:00:00-06:00",
        endTime: "2020-02-04T09:00:00-06:00",
        isDaytime: true,
        temperature: 23,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/day/snow?size=small",
        shortForecast: "Chance Light Snow",
        detailedForecast: ""
      },
      {
        number: 62,
        name: "",
        startTime: "2020-02-04T09:00:00-06:00",
        endTime: "2020-02-04T10:00:00-06:00",
        isDaytime: true,
        temperature: 23,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/day/snow?size=small",
        shortForecast: "Chance Light Snow",
        detailedForecast: ""
      },
      {
        number: 63,
        name: "",
        startTime: "2020-02-04T10:00:00-06:00",
        endTime: "2020-02-04T11:00:00-06:00",
        isDaytime: true,
        temperature: 23,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/day/snow?size=small",
        shortForecast: "Chance Light Snow",
        detailedForecast: ""
      },
      {
        number: 64,
        name: "",
        startTime: "2020-02-04T11:00:00-06:00",
        endTime: "2020-02-04T12:00:00-06:00",
        isDaytime: true,
        temperature: 23,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/day/snow?size=small",
        shortForecast: "Chance Light Snow",
        detailedForecast: ""
      },
      {
        number: 65,
        name: "",
        startTime: "2020-02-04T12:00:00-06:00",
        endTime: "2020-02-04T13:00:00-06:00",
        isDaytime: true,
        temperature: 23,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/day/snow?size=small",
        shortForecast: "Light Snow Likely",
        detailedForecast: ""
      },
      {
        number: 66,
        name: "",
        startTime: "2020-02-04T13:00:00-06:00",
        endTime: "2020-02-04T14:00:00-06:00",
        isDaytime: true,
        temperature: 24,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/day/snow?size=small",
        shortForecast: "Light Snow Likely",
        detailedForecast: ""
      },
      {
        number: 67,
        name: "",
        startTime: "2020-02-04T14:00:00-06:00",
        endTime: "2020-02-04T15:00:00-06:00",
        isDaytime: true,
        temperature: 24,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/day/snow?size=small",
        shortForecast: "Light Snow Likely",
        detailedForecast: ""
      },
      {
        number: 68,
        name: "",
        startTime: "2020-02-04T15:00:00-06:00",
        endTime: "2020-02-04T16:00:00-06:00",
        isDaytime: true,
        temperature: 25,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/day/snow?size=small",
        shortForecast: "Light Snow Likely",
        detailedForecast: ""
      },
      {
        number: 69,
        name: "",
        startTime: "2020-02-04T16:00:00-06:00",
        endTime: "2020-02-04T17:00:00-06:00",
        isDaytime: true,
        temperature: 25,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/day/snow?size=small",
        shortForecast: "Light Snow Likely",
        detailedForecast: ""
      },
      {
        number: 70,
        name: "",
        startTime: "2020-02-04T17:00:00-06:00",
        endTime: "2020-02-04T18:00:00-06:00",
        isDaytime: true,
        temperature: 25,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/day/snow?size=small",
        shortForecast: "Light Snow Likely",
        detailedForecast: ""
      },
      {
        number: 71,
        name: "",
        startTime: "2020-02-04T18:00:00-06:00",
        endTime: "2020-02-04T19:00:00-06:00",
        isDaytime: false,
        temperature: 24,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/night/snow?size=small",
        shortForecast: "Chance Light Snow",
        detailedForecast: ""
      },
      {
        number: 72,
        name: "",
        startTime: "2020-02-04T19:00:00-06:00",
        endTime: "2020-02-04T20:00:00-06:00",
        isDaytime: false,
        temperature: 23,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/night/snow?size=small",
        shortForecast: "Chance Light Snow",
        detailedForecast: ""
      },
      {
        number: 73,
        name: "",
        startTime: "2020-02-04T20:00:00-06:00",
        endTime: "2020-02-04T21:00:00-06:00",
        isDaytime: false,
        temperature: 23,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "N",
        icon: "https://api.weather.gov/icons/land/night/snow?size=small",
        shortForecast: "Chance Light Snow",
        detailedForecast: ""
      },
      {
        number: 74,
        name: "",
        startTime: "2020-02-04T21:00:00-06:00",
        endTime: "2020-02-04T22:00:00-06:00",
        isDaytime: false,
        temperature: 22,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "N",
        icon: "https://api.weather.gov/icons/land/night/snow?size=small",
        shortForecast: "Chance Light Snow",
        detailedForecast: ""
      },
      {
        number: 75,
        name: "",
        startTime: "2020-02-04T22:00:00-06:00",
        endTime: "2020-02-04T23:00:00-06:00",
        isDaytime: false,
        temperature: 22,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "N",
        icon: "https://api.weather.gov/icons/land/night/snow?size=small",
        shortForecast: "Chance Light Snow",
        detailedForecast: ""
      },
      {
        number: 76,
        name: "",
        startTime: "2020-02-04T23:00:00-06:00",
        endTime: "2020-02-05T00:00:00-06:00",
        isDaytime: false,
        temperature: 21,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "N",
        icon: "https://api.weather.gov/icons/land/night/snow?size=small",
        shortForecast: "Chance Light Snow",
        detailedForecast: ""
      },
      {
        number: 77,
        name: "",
        startTime: "2020-02-05T00:00:00-06:00",
        endTime: "2020-02-05T01:00:00-06:00",
        isDaytime: false,
        temperature: 21,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "N",
        icon: "https://api.weather.gov/icons/land/night/snow?size=small",
        shortForecast: "Chance Light Snow",
        detailedForecast: ""
      },
      {
        number: 78,
        name: "",
        startTime: "2020-02-05T01:00:00-06:00",
        endTime: "2020-02-05T02:00:00-06:00",
        isDaytime: false,
        temperature: 20,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "N",
        icon: "https://api.weather.gov/icons/land/night/snow?size=small",
        shortForecast: "Chance Light Snow",
        detailedForecast: ""
      },
      {
        number: 79,
        name: "",
        startTime: "2020-02-05T02:00:00-06:00",
        endTime: "2020-02-05T03:00:00-06:00",
        isDaytime: false,
        temperature: 20,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "N",
        icon: "https://api.weather.gov/icons/land/night/snow?size=small",
        shortForecast: "Chance Light Snow",
        detailedForecast: ""
      },
      {
        number: 80,
        name: "",
        startTime: "2020-02-05T03:00:00-06:00",
        endTime: "2020-02-05T04:00:00-06:00",
        isDaytime: false,
        temperature: 19,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "N",
        icon: "https://api.weather.gov/icons/land/night/snow?size=small",
        shortForecast: "Chance Light Snow",
        detailedForecast: ""
      },
      {
        number: 81,
        name: "",
        startTime: "2020-02-05T04:00:00-06:00",
        endTime: "2020-02-05T05:00:00-06:00",
        isDaytime: false,
        temperature: 18,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "N",
        icon: "https://api.weather.gov/icons/land/night/snow?size=small",
        shortForecast: "Chance Light Snow",
        detailedForecast: ""
      },
      {
        number: 82,
        name: "",
        startTime: "2020-02-05T05:00:00-06:00",
        endTime: "2020-02-05T06:00:00-06:00",
        isDaytime: false,
        temperature: 18,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "N",
        icon: "https://api.weather.gov/icons/land/night/snow?size=small",
        shortForecast: "Chance Light Snow",
        detailedForecast: ""
      },
      {
        number: 83,
        name: "",
        startTime: "2020-02-05T06:00:00-06:00",
        endTime: "2020-02-05T07:00:00-06:00",
        isDaytime: true,
        temperature: 18,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "N",
        icon: "https://api.weather.gov/icons/land/day/snow?size=small",
        shortForecast: "Slight Chance Light Snow",
        detailedForecast: ""
      },
      {
        number: 84,
        name: "",
        startTime: "2020-02-05T07:00:00-06:00",
        endTime: "2020-02-05T08:00:00-06:00",
        isDaytime: true,
        temperature: 18,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "N",
        icon: "https://api.weather.gov/icons/land/day/snow?size=small",
        shortForecast: "Slight Chance Light Snow",
        detailedForecast: ""
      },
      {
        number: 85,
        name: "",
        startTime: "2020-02-05T08:00:00-06:00",
        endTime: "2020-02-05T09:00:00-06:00",
        isDaytime: true,
        temperature: 18,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/day/snow?size=small",
        shortForecast: "Slight Chance Light Snow",
        detailedForecast: ""
      },
      {
        number: 86,
        name: "",
        startTime: "2020-02-05T09:00:00-06:00",
        endTime: "2020-02-05T10:00:00-06:00",
        isDaytime: true,
        temperature: 19,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/day/snow?size=small",
        shortForecast: "Slight Chance Light Snow",
        detailedForecast: ""
      },
      {
        number: 87,
        name: "",
        startTime: "2020-02-05T10:00:00-06:00",
        endTime: "2020-02-05T11:00:00-06:00",
        isDaytime: true,
        temperature: 20,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "N",
        icon: "https://api.weather.gov/icons/land/day/snow?size=small",
        shortForecast: "Slight Chance Light Snow",
        detailedForecast: ""
      },
      {
        number: 88,
        name: "",
        startTime: "2020-02-05T11:00:00-06:00",
        endTime: "2020-02-05T12:00:00-06:00",
        isDaytime: true,
        temperature: 22,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "N",
        icon: "https://api.weather.gov/icons/land/day/snow?size=small",
        shortForecast: "Slight Chance Light Snow",
        detailedForecast: ""
      },
      {
        number: 89,
        name: "",
        startTime: "2020-02-05T12:00:00-06:00",
        endTime: "2020-02-05T13:00:00-06:00",
        isDaytime: true,
        temperature: 23,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "N",
        icon: "https://api.weather.gov/icons/land/day/bkn?size=small",
        shortForecast: "Mostly Cloudy",
        detailedForecast: ""
      },
      {
        number: 90,
        name: "",
        startTime: "2020-02-05T13:00:00-06:00",
        endTime: "2020-02-05T14:00:00-06:00",
        isDaytime: true,
        temperature: 24,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "N",
        icon: "https://api.weather.gov/icons/land/day/bkn?size=small",
        shortForecast: "Mostly Cloudy",
        detailedForecast: ""
      },
      {
        number: 91,
        name: "",
        startTime: "2020-02-05T14:00:00-06:00",
        endTime: "2020-02-05T15:00:00-06:00",
        isDaytime: true,
        temperature: 25,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "N",
        icon: "https://api.weather.gov/icons/land/day/bkn?size=small",
        shortForecast: "Mostly Cloudy",
        detailedForecast: ""
      },
      {
        number: 92,
        name: "",
        startTime: "2020-02-05T15:00:00-06:00",
        endTime: "2020-02-05T16:00:00-06:00",
        isDaytime: true,
        temperature: 26,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "N",
        icon: "https://api.weather.gov/icons/land/day/bkn?size=small",
        shortForecast: "Partly Sunny",
        detailedForecast: ""
      },
      {
        number: 93,
        name: "",
        startTime: "2020-02-05T16:00:00-06:00",
        endTime: "2020-02-05T17:00:00-06:00",
        isDaytime: true,
        temperature: 26,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "N",
        icon: "https://api.weather.gov/icons/land/day/bkn?size=small",
        shortForecast: "Partly Sunny",
        detailedForecast: ""
      },
      {
        number: 94,
        name: "",
        startTime: "2020-02-05T17:00:00-06:00",
        endTime: "2020-02-05T18:00:00-06:00",
        isDaytime: true,
        temperature: 26,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "0 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/day/bkn?size=small",
        shortForecast: "Partly Sunny",
        detailedForecast: ""
      },
      {
        number: 95,
        name: "",
        startTime: "2020-02-05T18:00:00-06:00",
        endTime: "2020-02-05T19:00:00-06:00",
        isDaytime: false,
        temperature: 25,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "0 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/night/sct?size=small",
        shortForecast: "Partly Cloudy",
        detailedForecast: ""
      },
      {
        number: 96,
        name: "",
        startTime: "2020-02-05T19:00:00-06:00",
        endTime: "2020-02-05T20:00:00-06:00",
        isDaytime: false,
        temperature: 24,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "0 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/night/sct?size=small",
        shortForecast: "Partly Cloudy",
        detailedForecast: ""
      },
      {
        number: 97,
        name: "",
        startTime: "2020-02-05T20:00:00-06:00",
        endTime: "2020-02-05T21:00:00-06:00",
        isDaytime: false,
        temperature: 22,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "0 mph",
        windDirection: "N",
        icon: "https://api.weather.gov/icons/land/night/sct?size=small",
        shortForecast: "Partly Cloudy",
        detailedForecast: ""
      },
      {
        number: 98,
        name: "",
        startTime: "2020-02-05T21:00:00-06:00",
        endTime: "2020-02-05T22:00:00-06:00",
        isDaytime: false,
        temperature: 21,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "0 mph",
        windDirection: "N",
        icon: "https://api.weather.gov/icons/land/night/sct?size=small",
        shortForecast: "Partly Cloudy",
        detailedForecast: ""
      },
      {
        number: 99,
        name: "",
        startTime: "2020-02-05T22:00:00-06:00",
        endTime: "2020-02-05T23:00:00-06:00",
        isDaytime: false,
        temperature: 20,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "0 mph",
        windDirection: "NW",
        icon: "https://api.weather.gov/icons/land/night/sct?size=small",
        shortForecast: "Partly Cloudy",
        detailedForecast: ""
      },
      {
        number: 100,
        name: "",
        startTime: "2020-02-05T23:00:00-06:00",
        endTime: "2020-02-06T00:00:00-06:00",
        isDaytime: false,
        temperature: 20,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "0 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/night/sct?size=small",
        shortForecast: "Partly Cloudy",
        detailedForecast: ""
      },
      {
        number: 101,
        name: "",
        startTime: "2020-02-06T00:00:00-06:00",
        endTime: "2020-02-06T01:00:00-06:00",
        isDaytime: false,
        temperature: 19,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "0 mph",
        windDirection: "SW",
        icon: "https://api.weather.gov/icons/land/night/sct?size=small",
        shortForecast: "Partly Cloudy",
        detailedForecast: ""
      },
      {
        number: 102,
        name: "",
        startTime: "2020-02-06T01:00:00-06:00",
        endTime: "2020-02-06T02:00:00-06:00",
        isDaytime: false,
        temperature: 18,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "0 mph",
        windDirection: "SW",
        icon: "https://api.weather.gov/icons/land/night/sct?size=small",
        shortForecast: "Partly Cloudy",
        detailedForecast: ""
      },
      {
        number: 103,
        name: "",
        startTime: "2020-02-06T02:00:00-06:00",
        endTime: "2020-02-06T03:00:00-06:00",
        isDaytime: false,
        temperature: 18,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "0 mph",
        windDirection: "SW",
        icon: "https://api.weather.gov/icons/land/night/sct?size=small",
        shortForecast: "Partly Cloudy",
        detailedForecast: ""
      },
      {
        number: 104,
        name: "",
        startTime: "2020-02-06T03:00:00-06:00",
        endTime: "2020-02-06T04:00:00-06:00",
        isDaytime: false,
        temperature: 17,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "0 mph",
        windDirection: "SW",
        icon: "https://api.weather.gov/icons/land/night/few?size=small",
        shortForecast: "Mostly Clear",
        detailedForecast: ""
      },
      {
        number: 105,
        name: "",
        startTime: "2020-02-06T04:00:00-06:00",
        endTime: "2020-02-06T05:00:00-06:00",
        isDaytime: false,
        temperature: 16,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "SW",
        icon: "https://api.weather.gov/icons/land/night/few?size=small",
        shortForecast: "Mostly Clear",
        detailedForecast: ""
      },
      {
        number: 106,
        name: "",
        startTime: "2020-02-06T05:00:00-06:00",
        endTime: "2020-02-06T06:00:00-06:00",
        isDaytime: false,
        temperature: 16,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/night/few?size=small",
        shortForecast: "Mostly Clear",
        detailedForecast: ""
      },
      {
        number: 107,
        name: "",
        startTime: "2020-02-06T06:00:00-06:00",
        endTime: "2020-02-06T07:00:00-06:00",
        isDaytime: true,
        temperature: 16,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/day/few?size=small",
        shortForecast: "Sunny",
        detailedForecast: ""
      },
      {
        number: 108,
        name: "",
        startTime: "2020-02-06T07:00:00-06:00",
        endTime: "2020-02-06T08:00:00-06:00",
        isDaytime: true,
        temperature: 17,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/day/few?size=small",
        shortForecast: "Sunny",
        detailedForecast: ""
      },
      {
        number: 109,
        name: "",
        startTime: "2020-02-06T08:00:00-06:00",
        endTime: "2020-02-06T09:00:00-06:00",
        isDaytime: true,
        temperature: 18,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/day/few?size=small",
        shortForecast: "Sunny",
        detailedForecast: ""
      },
      {
        number: 110,
        name: "",
        startTime: "2020-02-06T09:00:00-06:00",
        endTime: "2020-02-06T10:00:00-06:00",
        isDaytime: true,
        temperature: 20,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/day/few?size=small",
        shortForecast: "Sunny",
        detailedForecast: ""
      },
      {
        number: 111,
        name: "",
        startTime: "2020-02-06T10:00:00-06:00",
        endTime: "2020-02-06T11:00:00-06:00",
        isDaytime: true,
        temperature: 23,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/day/few?size=small",
        shortForecast: "Sunny",
        detailedForecast: ""
      },
      {
        number: 112,
        name: "",
        startTime: "2020-02-06T11:00:00-06:00",
        endTime: "2020-02-06T12:00:00-06:00",
        isDaytime: true,
        temperature: 27,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/day/few?size=small",
        shortForecast: "Sunny",
        detailedForecast: ""
      },
      {
        number: 113,
        name: "",
        startTime: "2020-02-06T12:00:00-06:00",
        endTime: "2020-02-06T13:00:00-06:00",
        isDaytime: true,
        temperature: 30,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/day/few?size=small",
        shortForecast: "Sunny",
        detailedForecast: ""
      },
      {
        number: 114,
        name: "",
        startTime: "2020-02-06T13:00:00-06:00",
        endTime: "2020-02-06T14:00:00-06:00",
        isDaytime: true,
        temperature: 32,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/day/few?size=small",
        shortForecast: "Sunny",
        detailedForecast: ""
      },
      {
        number: 115,
        name: "",
        startTime: "2020-02-06T14:00:00-06:00",
        endTime: "2020-02-06T15:00:00-06:00",
        isDaytime: true,
        temperature: 34,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/day/sct?size=small",
        shortForecast: "Mostly Sunny",
        detailedForecast: ""
      },
      {
        number: 116,
        name: "",
        startTime: "2020-02-06T15:00:00-06:00",
        endTime: "2020-02-06T16:00:00-06:00",
        isDaytime: true,
        temperature: 35,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/day/sct?size=small",
        shortForecast: "Mostly Sunny",
        detailedForecast: ""
      },
      {
        number: 117,
        name: "",
        startTime: "2020-02-06T16:00:00-06:00",
        endTime: "2020-02-06T17:00:00-06:00",
        isDaytime: true,
        temperature: 35,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/day/sct?size=small",
        shortForecast: "Mostly Sunny",
        detailedForecast: ""
      },
      {
        number: 118,
        name: "",
        startTime: "2020-02-06T17:00:00-06:00",
        endTime: "2020-02-06T18:00:00-06:00",
        isDaytime: true,
        temperature: 34,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/day/sct?size=small",
        shortForecast: "Mostly Sunny",
        detailedForecast: ""
      },
      {
        number: 119,
        name: "",
        startTime: "2020-02-06T18:00:00-06:00",
        endTime: "2020-02-06T19:00:00-06:00",
        isDaytime: false,
        temperature: 33,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/night/bkn?size=small",
        shortForecast: "Mostly Cloudy",
        detailedForecast: ""
      },
      {
        number: 120,
        name: "",
        startTime: "2020-02-06T19:00:00-06:00",
        endTime: "2020-02-06T20:00:00-06:00",
        isDaytime: false,
        temperature: 32,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/night/bkn?size=small",
        shortForecast: "Mostly Cloudy",
        detailedForecast: ""
      },
      {
        number: 121,
        name: "",
        startTime: "2020-02-06T20:00:00-06:00",
        endTime: "2020-02-06T21:00:00-06:00",
        isDaytime: false,
        temperature: 32,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/night/bkn?size=small",
        shortForecast: "Mostly Cloudy",
        detailedForecast: ""
      },
      {
        number: 122,
        name: "",
        startTime: "2020-02-06T21:00:00-06:00",
        endTime: "2020-02-06T22:00:00-06:00",
        isDaytime: false,
        temperature: 31,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/night/bkn?size=small",
        shortForecast: "Mostly Cloudy",
        detailedForecast: ""
      },
      {
        number: 123,
        name: "",
        startTime: "2020-02-06T22:00:00-06:00",
        endTime: "2020-02-06T23:00:00-06:00",
        isDaytime: false,
        temperature: 31,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/night/bkn?size=small",
        shortForecast: "Mostly Cloudy",
        detailedForecast: ""
      },
      {
        number: 124,
        name: "",
        startTime: "2020-02-06T23:00:00-06:00",
        endTime: "2020-02-07T00:00:00-06:00",
        isDaytime: false,
        temperature: 31,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/night/bkn?size=small",
        shortForecast: "Mostly Cloudy",
        detailedForecast: ""
      },
      {
        number: 125,
        name: "",
        startTime: "2020-02-07T00:00:00-06:00",
        endTime: "2020-02-07T01:00:00-06:00",
        isDaytime: false,
        temperature: 31,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/night/bkn?size=small",
        shortForecast: "Mostly Cloudy",
        detailedForecast: ""
      },
      {
        number: 126,
        name: "",
        startTime: "2020-02-07T01:00:00-06:00",
        endTime: "2020-02-07T02:00:00-06:00",
        isDaytime: false,
        temperature: 30,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/night/bkn?size=small",
        shortForecast: "Mostly Cloudy",
        detailedForecast: ""
      },
      {
        number: 127,
        name: "",
        startTime: "2020-02-07T02:00:00-06:00",
        endTime: "2020-02-07T03:00:00-06:00",
        isDaytime: false,
        temperature: 30,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/night/bkn?size=small",
        shortForecast: "Mostly Cloudy",
        detailedForecast: ""
      },
      {
        number: 128,
        name: "",
        startTime: "2020-02-07T03:00:00-06:00",
        endTime: "2020-02-07T04:00:00-06:00",
        isDaytime: false,
        temperature: 29,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/night/bkn?size=small",
        shortForecast: "Mostly Cloudy",
        detailedForecast: ""
      },
      {
        number: 129,
        name: "",
        startTime: "2020-02-07T04:00:00-06:00",
        endTime: "2020-02-07T05:00:00-06:00",
        isDaytime: false,
        temperature: 29,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/night/bkn?size=small",
        shortForecast: "Mostly Cloudy",
        detailedForecast: ""
      },
      {
        number: 130,
        name: "",
        startTime: "2020-02-07T05:00:00-06:00",
        endTime: "2020-02-07T06:00:00-06:00",
        isDaytime: false,
        temperature: 30,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/night/sct?size=small",
        shortForecast: "Partly Cloudy",
        detailedForecast: ""
      },
      {
        number: 131,
        name: "",
        startTime: "2020-02-07T06:00:00-06:00",
        endTime: "2020-02-07T07:00:00-06:00",
        isDaytime: true,
        temperature: 30,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/day/sct?size=small",
        shortForecast: "Mostly Sunny",
        detailedForecast: ""
      },
      {
        number: 132,
        name: "",
        startTime: "2020-02-07T07:00:00-06:00",
        endTime: "2020-02-07T08:00:00-06:00",
        isDaytime: true,
        temperature: 30,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/day/sct?size=small",
        shortForecast: "Mostly Sunny",
        detailedForecast: ""
      },
      {
        number: 133,
        name: "",
        startTime: "2020-02-07T08:00:00-06:00",
        endTime: "2020-02-07T09:00:00-06:00",
        isDaytime: true,
        temperature: 30,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/day/sct?size=small",
        shortForecast: "Mostly Sunny",
        detailedForecast: ""
      },
      {
        number: 134,
        name: "",
        startTime: "2020-02-07T09:00:00-06:00",
        endTime: "2020-02-07T10:00:00-06:00",
        isDaytime: true,
        temperature: 31,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/day/sct?size=small",
        shortForecast: "Mostly Sunny",
        detailedForecast: ""
      },
      {
        number: 135,
        name: "",
        startTime: "2020-02-07T10:00:00-06:00",
        endTime: "2020-02-07T11:00:00-06:00",
        isDaytime: true,
        temperature: 33,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NW",
        icon: "https://api.weather.gov/icons/land/day/sct?size=small",
        shortForecast: "Mostly Sunny",
        detailedForecast: ""
      },
      {
        number: 136,
        name: "",
        startTime: "2020-02-07T11:00:00-06:00",
        endTime: "2020-02-07T12:00:00-06:00",
        isDaytime: true,
        temperature: 35,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NW",
        icon: "https://api.weather.gov/icons/land/day/sct?size=small",
        shortForecast: "Mostly Sunny",
        detailedForecast: ""
      },
      {
        number: 137,
        name: "",
        startTime: "2020-02-07T12:00:00-06:00",
        endTime: "2020-02-07T13:00:00-06:00",
        isDaytime: true,
        temperature: 37,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NW",
        icon: "https://api.weather.gov/icons/land/day/sct?size=small",
        shortForecast: "Mostly Sunny",
        detailedForecast: ""
      },
      {
        number: 138,
        name: "",
        startTime: "2020-02-07T13:00:00-06:00",
        endTime: "2020-02-07T14:00:00-06:00",
        isDaytime: true,
        temperature: 39,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NW",
        icon: "https://api.weather.gov/icons/land/day/sct?size=small",
        shortForecast: "Mostly Sunny",
        detailedForecast: ""
      },
      {
        number: 139,
        name: "",
        startTime: "2020-02-07T14:00:00-06:00",
        endTime: "2020-02-07T15:00:00-06:00",
        isDaytime: true,
        temperature: 40,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NW",
        icon: "https://api.weather.gov/icons/land/day/bkn?size=small",
        shortForecast: "Partly Sunny",
        detailedForecast: ""
      },
      {
        number: 140,
        name: "",
        startTime: "2020-02-07T15:00:00-06:00",
        endTime: "2020-02-07T16:00:00-06:00",
        isDaytime: true,
        temperature: 40,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "NW",
        icon: "https://api.weather.gov/icons/land/day/bkn?size=small",
        shortForecast: "Partly Sunny",
        detailedForecast: ""
      },
      {
        number: 141,
        name: "",
        startTime: "2020-02-07T16:00:00-06:00",
        endTime: "2020-02-07T17:00:00-06:00",
        isDaytime: true,
        temperature: 39,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "NW",
        icon: "https://api.weather.gov/icons/land/day/bkn?size=small",
        shortForecast: "Partly Sunny",
        detailedForecast: ""
      },
      {
        number: 142,
        name: "",
        startTime: "2020-02-07T17:00:00-06:00",
        endTime: "2020-02-07T18:00:00-06:00",
        isDaytime: true,
        temperature: 38,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 mph",
        windDirection: "NW",
        icon: "https://api.weather.gov/icons/land/day/bkn?size=small",
        shortForecast: "Partly Sunny",
        detailedForecast: ""
      },
      {
        number: 143,
        name: "",
        startTime: "2020-02-07T18:00:00-06:00",
        endTime: "2020-02-07T19:00:00-06:00",
        isDaytime: false,
        temperature: 36,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "NW",
        icon: "https://api.weather.gov/icons/land/night/bkn?size=small",
        shortForecast: "Mostly Cloudy",
        detailedForecast: ""
      },
      {
        number: 144,
        name: "",
        startTime: "2020-02-07T19:00:00-06:00",
        endTime: "2020-02-07T20:00:00-06:00",
        isDaytime: false,
        temperature: 34,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "NW",
        icon: "https://api.weather.gov/icons/land/night/bkn?size=small",
        shortForecast: "Mostly Cloudy",
        detailedForecast: ""
      },
      {
        number: 145,
        name: "",
        startTime: "2020-02-07T20:00:00-06:00",
        endTime: "2020-02-07T21:00:00-06:00",
        isDaytime: false,
        temperature: 32,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "N",
        icon: "https://api.weather.gov/icons/land/night/bkn?size=small",
        shortForecast: "Mostly Cloudy",
        detailedForecast: ""
      },
      {
        number: 146,
        name: "",
        startTime: "2020-02-07T21:00:00-06:00",
        endTime: "2020-02-07T22:00:00-06:00",
        isDaytime: false,
        temperature: 31,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "N",
        icon: "https://api.weather.gov/icons/land/night/sct?size=small",
        shortForecast: "Partly Cloudy",
        detailedForecast: ""
      },
      {
        number: 147,
        name: "",
        startTime: "2020-02-07T22:00:00-06:00",
        endTime: "2020-02-07T23:00:00-06:00",
        isDaytime: false,
        temperature: 30,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "NW",
        icon: "https://api.weather.gov/icons/land/night/sct?size=small",
        shortForecast: "Partly Cloudy",
        detailedForecast: ""
      },
      {
        number: 148,
        name: "",
        startTime: "2020-02-07T23:00:00-06:00",
        endTime: "2020-02-08T00:00:00-06:00",
        isDaytime: false,
        temperature: 30,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "NW",
        icon: "https://api.weather.gov/icons/land/night/sct?size=small",
        shortForecast: "Partly Cloudy",
        detailedForecast: ""
      },
      {
        number: 149,
        name: "",
        startTime: "2020-02-08T00:00:00-06:00",
        endTime: "2020-02-08T01:00:00-06:00",
        isDaytime: false,
        temperature: 29,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/night/sct?size=small",
        shortForecast: "Partly Cloudy",
        detailedForecast: ""
      },
      {
        number: 150,
        name: "",
        startTime: "2020-02-08T01:00:00-06:00",
        endTime: "2020-02-08T02:00:00-06:00",
        isDaytime: false,
        temperature: 28,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/night/sct?size=small",
        shortForecast: "Partly Cloudy",
        detailedForecast: ""
      },
      {
        number: 151,
        name: "",
        startTime: "2020-02-08T02:00:00-06:00",
        endTime: "2020-02-08T03:00:00-06:00",
        isDaytime: false,
        temperature: 28,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/night/sct?size=small",
        shortForecast: "Partly Cloudy",
        detailedForecast: ""
      },
      {
        number: 152,
        name: "",
        startTime: "2020-02-08T03:00:00-06:00",
        endTime: "2020-02-08T04:00:00-06:00",
        isDaytime: false,
        temperature: 27,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/night/sct?size=small",
        shortForecast: "Partly Cloudy",
        detailedForecast: ""
      },
      {
        number: 153,
        name: "",
        startTime: "2020-02-08T04:00:00-06:00",
        endTime: "2020-02-08T05:00:00-06:00",
        isDaytime: false,
        temperature: 27,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/night/sct?size=small",
        shortForecast: "Partly Cloudy",
        detailedForecast: ""
      },
      {
        number: 154,
        name: "",
        startTime: "2020-02-08T05:00:00-06:00",
        endTime: "2020-02-08T06:00:00-06:00",
        isDaytime: false,
        temperature: 27,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "N",
        icon: "https://api.weather.gov/icons/land/night/sct?size=small",
        shortForecast: "Partly Cloudy",
        detailedForecast: ""
      },
      {
        number: 155,
        name: "",
        startTime: "2020-02-08T06:00:00-06:00",
        endTime: "2020-02-08T07:00:00-06:00",
        isDaytime: true,
        temperature: 27,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "N",
        icon: "https://api.weather.gov/icons/land/day/sct?size=small",
        shortForecast: "Mostly Sunny",
        detailedForecast: ""
      },
      {
        number: 156,
        name: "",
        startTime: "2020-02-08T07:00:00-06:00",
        endTime: "2020-02-08T08:00:00-06:00",
        isDaytime: true,
        temperature: 27,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "N",
        icon: "https://api.weather.gov/icons/land/day/sct?size=small",
        shortForecast: "Mostly Sunny",
        detailedForecast: ""
      }
    ]
  }
};

const sevenDay = {
  "@context": [
    "https://raw.githubusercontent.com/geojson/geojson-ld/master/contexts/geojson-base.jsonld",
    {
      wx: "https://api.weather.gov/ontology#",
      geo: "http://www.opengis.net/ont/geosparql#",
      unit: "http://codes.wmo.int/common/unit/",
      "@vocab": "https://api.weather.gov/ontology#"
    }
  ],
  type: "Feature",
  geometry: {
    type: "GeometryCollection",
    geometries: [
      {
        type: "Point",
        coordinates: [-97.094408400000006, 39.7559738]
      },
      {
        type: "Polygon",
        coordinates: [
          [
            [-97.1089731, 39.766826299999998],
            [-97.108526900000001, 39.744778799999999],
            [-97.079846700000004, 39.745119500000001],
            [-97.08028680000001, 39.767167000000001],
            [-97.1089731, 39.766826299999998]
          ]
        ]
      }
    ]
  },
  properties: {
    updated: "2020-02-02T13:26:04+00:00",
    units: "us",
    forecastGenerator: "BaselineForecastGenerator",
    generatedAt: "2020-02-02T14:00:42+00:00",
    updateTime: "2020-02-02T13:26:04+00:00",
    validTimes: "2020-02-02T07:00:00+00:00/P7DT18H",
    elevation: {
      value: 441.96000000000004,
      unitCode: "unit:m"
    },
    periods: [
      {
        number: 1,
        name: "Today",
        startTime: "2020-02-02T08:00:00-06:00",
        endTime: "2020-02-02T18:00:00-06:00",
        isDaytime: true,
        temperature: 65,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "0 to 10 mph",
        windDirection: "NW",
        icon: "https://api.weather.gov/icons/land/day/few?size=medium",
        shortForecast: "Sunny",
        detailedForecast:
          "Sunny, with a high near 65. Northwest wind 0 to 10 mph."
      },
      {
        number: 2,
        name: "Tonight",
        startTime: "2020-02-02T18:00:00-06:00",
        endTime: "2020-02-03T06:00:00-06:00",
        isDaytime: false,
        temperature: 33,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 to 10 mph",
        windDirection: "E",
        icon:
          "https://api.weather.gov/icons/land/night/bkn/rain,20?size=medium",
        shortForecast: "Mostly Cloudy then Slight Chance Drizzle",
        detailedForecast:
          "A slight chance of drizzle after 5am. Mostly cloudy, with a low around 33. East wind 5 to 10 mph. Chance of precipitation is 20%."
      },
      {
        number: 3,
        name: "Monday",
        startTime: "2020-02-03T06:00:00-06:00",
        endTime: "2020-02-03T18:00:00-06:00",
        isDaytime: true,
        temperature: 36,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "10 to 15 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/day/rain,20?size=medium",
        shortForecast: "Slight Chance Drizzle",
        detailedForecast:
          "A slight chance of drizzle. Cloudy, with a high near 36. Northeast wind 10 to 15 mph, with gusts as high as 25 mph. Chance of precipitation is 20%."
      },
      {
        number: 4,
        name: "Monday Night",
        startTime: "2020-02-03T18:00:00-06:00",
        endTime: "2020-02-04T06:00:00-06:00",
        isDaytime: false,
        temperature: 21,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "NE",
        icon:
          "https://api.weather.gov/icons/land/night/ovc/snow,30?size=medium",
        shortForecast: "Cloudy then Chance Light Snow",
        detailedForecast:
          "A chance of snow and a slight chance of freezing drizzle after midnight. Cloudy, with a low around 21. Northeast wind around 15 mph, with gusts as high as 30 mph. Chance of precipitation is 30%. New snow accumulation of less than half an inch possible."
      },
      {
        number: 5,
        name: "Tuesday",
        startTime: "2020-02-04T06:00:00-06:00",
        endTime: "2020-02-04T18:00:00-06:00",
        isDaytime: true,
        temperature: 24,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "15 mph",
        windDirection: "N",
        icon: "https://api.weather.gov/icons/land/day/snow,50?size=medium",
        shortForecast: "Chance Light Snow",
        detailedForecast:
          "A chance of snow. Cloudy, with a high near 24. North wind around 15 mph, with gusts as high as 30 mph. Chance of precipitation is 50%. New snow accumulation of less than half an inch possible."
      },
      {
        number: 6,
        name: "Tuesday Night",
        startTime: "2020-02-04T18:00:00-06:00",
        endTime: "2020-02-05T06:00:00-06:00",
        isDaytime: false,
        temperature: 17,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 to 15 mph",
        windDirection: "N",
        icon:
          "https://api.weather.gov/icons/land/night/snow,40/snow,20?size=medium",
        shortForecast: "Chance Light Snow",
        detailedForecast:
          "A chance of snow. Partly cloudy, with a low around 17. Chance of precipitation is 40%."
      },
      {
        number: 7,
        name: "Wednesday",
        startTime: "2020-02-05T06:00:00-06:00",
        endTime: "2020-02-05T18:00:00-06:00",
        isDaytime: true,
        temperature: 28,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "NE",
        icon: "https://api.weather.gov/icons/land/day/snow,20/few?size=medium",
        shortForecast: "Slight Chance Light Snow then Sunny",
        detailedForecast:
          "A slight chance of snow before noon. Sunny, with a high near 28. Chance of precipitation is 20%."
      },
      {
        number: 8,
        name: "Wednesday Night",
        startTime: "2020-02-05T18:00:00-06:00",
        endTime: "2020-02-06T06:00:00-06:00",
        isDaytime: false,
        temperature: 17,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "NW",
        icon: "https://api.weather.gov/icons/land/night/few?size=medium",
        shortForecast: "Mostly Clear",
        detailedForecast: "Mostly clear, with a low around 17."
      },
      {
        number: 9,
        name: "Thursday",
        startTime: "2020-02-06T06:00:00-06:00",
        endTime: "2020-02-06T18:00:00-06:00",
        isDaytime: true,
        temperature: 38,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "SW",
        icon: "https://api.weather.gov/icons/land/day/few?size=medium",
        shortForecast: "Sunny",
        detailedForecast: "Sunny, with a high near 38."
      },
      {
        number: 10,
        name: "Thursday Night",
        startTime: "2020-02-06T18:00:00-06:00",
        endTime: "2020-02-07T06:00:00-06:00",
        isDaytime: false,
        temperature: 26,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 to 10 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/night/bkn?size=medium",
        shortForecast: "Mostly Cloudy",
        detailedForecast: "Mostly cloudy, with a low around 26."
      },
      {
        number: 11,
        name: "Friday",
        startTime: "2020-02-07T06:00:00-06:00",
        endTime: "2020-02-07T18:00:00-06:00",
        isDaytime: true,
        temperature: 42,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 to 10 mph",
        windDirection: "NW",
        icon: "https://api.weather.gov/icons/land/day/bkn?size=medium",
        shortForecast: "Partly Sunny",
        detailedForecast: "Partly sunny, with a high near 42."
      },
      {
        number: 12,
        name: "Friday Night",
        startTime: "2020-02-07T18:00:00-06:00",
        endTime: "2020-02-08T06:00:00-06:00",
        isDaytime: false,
        temperature: 27,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "NW",
        icon: "https://api.weather.gov/icons/land/night/bkn?size=medium",
        shortForecast: "Mostly Cloudy",
        detailedForecast: "Mostly cloudy, with a low around 27."
      },
      {
        number: 13,
        name: "Saturday",
        startTime: "2020-02-08T06:00:00-06:00",
        endTime: "2020-02-08T18:00:00-06:00",
        isDaytime: true,
        temperature: 44,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 to 10 mph",
        windDirection: "W",
        icon: "https://api.weather.gov/icons/land/day/few?size=medium",
        shortForecast: "Sunny",
        detailedForecast: "Sunny, with a high near 44."
      },
      {
        number: 14,
        name: "Saturday Night",
        startTime: "2020-02-08T18:00:00-06:00",
        endTime: "2020-02-09T06:00:00-06:00",
        isDaytime: false,
        temperature: 28,
        temperatureUnit: "F",
        temperatureTrend: null,
        windSpeed: "5 mph",
        windDirection: "SW",
        icon: "https://api.weather.gov/icons/land/night/few?size=medium",
        shortForecast: "Mostly Clear",
        detailedForecast: "Mostly clear, with a low around 28."
      }
    ]
  }
};

export default {
  hourly,
  sevenDay
};
